const useCategory = () => {
  const categoryList = ["housing", "services", "forSale", "jobs"];
  const subCategoryList = {
    housing: [
      { id: "apt_for_rent", label: "Apartment for rent" },
      { id: "apt_for_share", label: "Apartment for share" },
      { id: "apt_for_sale", label: "Apartment for sale" },
      { id: "house_swap", label: "House Swap/Exchange" },
      { id: "house_sale", label: "House for Sale" },
      { id: "house_rent", label: "House for Rent" },
      { id: "room_rent", label: "Room for Rent" },
      { id: "room_share", label: "Room for Share" },
      { id: "land_sale", label: "Land for Sale" },
      { id: "land_rent", label: "Land for Rent" },
    ],
    services: [
      { id: "Automotive", label: "Automotive" },
      { id: "Beauty", label: "Beauty" },
      { id: "Cell_mobile", label: "Cell/mobile" },
      { id: "Computer", label: "Computer" },
      { id: "Event", label: "Event" },
      { id: "Farm+garden", label: "Farm+garden" },
      { id: "Health_well", label: "Health/well" },
      { id: "Household", label: "Household" },
      { id: "Labor_move", label: "Labor/move" },
      { id: "Legal", label: "Legal" },
      { id: "Teaching for kids", label: "Teaching for kids" },
    ],
    forSale: [
      { id: "Appliances", label: "Appliances" },
      { id: "Arts_Craft", label: "Arts / Craft" },
      { id: "Auto_parts", label: "Auto parts" },
      { id: "Aviation", label: "Aviation" },
      { id: "Baby+Kid_thins", label: "Baby+Kid thins" },
      { id: "Pet_animals", label: "Pet animals" },
      { id: "Beauty_health", label: "Beauty+health" },
      { id: "Bikes", label: "Bikes" },
      { id: "Bike parts", label: "Bike parts" },
      { id: "Books", label: "Books" },
      { id: "Business", label: "Business" },
      { id: "Cars_trucks_bus", label: "Cars / trucks / bus" },
      { id: "Cell Phones", label: "Cell Phones" },
      { id: "Cloths", label: "Cloths" },
      { id: "Computers", label: "Computers" },
      { id: "Computer parts", label: "Computer parts" },
      { id: "Electronics", label: "Electronics" },
      { id: "Farm_Garden", label: "Farm / Garden" },
      { id: "Free", label: "Free" },
      { id: "Furniture", label: "Furniture" },
      { id: "General", label: "General" },
      { id: "Heavy equipment", label: "Heavy equipment" },
      { id: "Households", label: "Households" },
      { id: "Jewelry", label: "Jewelry" },
      { id: "Sporting", label: "Sporting" },
      { id: "Tickets", label: "Tickets" },
      { id: "Tools", label: "Tools" },
      { id: "Toys_Games", label: "Toys+Games" },
      { id: "Wheels_tires", label: "Wheels / tires" },
    ],

    jobs: [
      { id: "Admin_Office", label: "Admin / Office" },
      { id: "Arch_Engineering", label: "Arch / Engineering" },
      { id: "Art_Media_Design", label: "Art / Media / Design" },
      { id: "Biotech_Science", label: "Biotech / Science" },
      { id: "Business_Mgmt", label: "Business / Mgmt" },
      { id: "Customer_Service", label: "Customer Service" },
      { id: "Education", label: "Education" },
      { id: "Food_Bev_Hosp", label: "Food / Bev / Hosp" },
      { id: "General_Labor", label: "General Labor" },
      { id: "Government", label: "Government" },
      { id: "Human_Resources", label: "Human Resources" },
      { id: "Legal_Paralegal", label: "Legal / Paralegal" },
      { id: "Manufacturing", label: "Manufacturing" },
      { id: "Marketing_Pr_Ad", label: "Marketing / Pr / Ad" },
      { id: "Medical_Health", label: "Medical / Health" },
      { id: "Nonprofit_Sector", label: "Nonprofit Sector" },
      { id: "Real_Estate", label: " Real Estate" },
      { id: "Retail_Wholesale", label: "Retail / Wholesale" },
      { id: "Sales", label: "Sales" },
      { id: "Security", label: "Security" },
      { id: "Salon_Spa_Fitness", label: "Salon / Spa / Fitness" },
      { id: "Skilled_Trade_Craft", label: "Skilled Trade / Craft" },
      { id: "Software_Qa_Dba", label: "Software / Qa / Dba" },
      { id: "Systems_Network", label: "Systems / Network" },
      { id: "Technical_Support", label: "Technical Support" },
      { id: "Transport", label: "Transport" },
      { id: "Tv_Film_Video", label: "Tv / Film / Video" },
      { id: "Web_Info_Design", label: "Web / Info Design" },
      { id: "Writing_Editing", label: "Writing / Editing" },
    ],
  };

  return { categoryList, subCategoryList };
};

export default useCategory;
